### ISSUE TITLE
Remover bitcode no build do SDK

### ISSUE THREAD

**Issue by luanupe** [acesso-io/unico-check-ios#112]
Bitcode impedindo upload para AppStoreConnect

<img width="1027" alt="Captura de Tela 2024-09-20 às 15 38 19" src="https://github.com/user-attachments/assets/acbe000f-14d4-4081-b2c6-bdbca2179a21">

**Comment by pgneri** [comment]
@luanupe eu estava com o mesmo problema, no Xcode 16 enquanto estava com cocoapods, mudei pro SPM, na ultima versão do sdk e resolveu.

**Comment by luanupe** [comment]
@pgneri obrigado pela dica! de fato estou usando cocoapods no projeto, mas optei por continuar por enquanto... usei o workaround apontado nessa thread do [Stackoverflow](https://stackoverflow.com/questions/78993520/invalid-executable-the-executable-appname-app-frameworks-hermes-framework-herm)
